# Import Library

In [1]:
import pandas as pd
import numpy as np
import mysql.connector 
import warnings
warnings.filterwarnings('ignore')

# SQL to Pythone Connect

In [2]:
conn  = mysql.connector.connect(
    user = 'root',
    password = 'sachin90',
    host = 'localhost',
    database = 'ott_analytics'
)
print("connection successfull")

connection successfull

# SQL Query Write

In [3]:
users = pd.read_sql('select * from users;',conn)
movie_series = pd.read_sql('select * from Movies_Series;',conn)
subscriptions = pd.read_sql('select * from Subscriptions;',conn)
watch_history =pd.read_sql('select * from watch_history;',conn)
recommendations = pd.read_sql('select * from Recommendations;',conn)
ratings_reviews =pd.read_sql('select * from Ratings_Reviews;',conn)
playback_events = pd.read_sql('select * from Playback_Events;',conn)
marketing_campaigns=pd.read_sql('select * from Marketing_Campaigns;',conn)
customer_complaints= pd.read_sql('select * from Customer_Complaints;',conn)

In [4]:
print('users',users.shape)
print('movie_series',movie_series.shape)
print('subscriptions',subscriptions.shape)
print('watch_history',watch_history.shape)
print('recommendations',recommendations.shape)
print('ratings_reviews',ratings_reviews.shape)
print('playback_events',playback_events.shape)
print('marketing_campaigns',marketing_campaigns.shape)
print('customer_complaints',customer_complaints.shape)

users (500000, 10)
movie_series (5000, 10)
subscriptions (800000, 10)
watch_history (5000000, 10)
recommendations (2000000, 9)
ratings_reviews (1000000, 7)
playback_events (4000000, 9)
marketing_campaigns (25000, 9)
customer_complaints (200000, 8)

# Connection Close

In [5]:
## conncetion close
conn.close()
print("Connection Closed")

Connection Closed

# All Table save in csv File

In [6]:
data = {
    "users": users,
    "subscriptions": subscriptions,
    "movie_series": movie_series,
    "watch_history": watch_history,
    "recommendations": recommendations,
    "ratings_reviews": ratings_reviews,
     "playback_events": playback_events,
    "marketing_campaigns": marketing_campaigns,
    "customer_complaints": customer_complaints
 }

for name, df in data.items():
    df.to_csv(fr"C:\Users\DELL\Downloads\Movie_Ott_Project_File\{name}.csv", index=False)

# Data Understanding

# users_table

In [7]:
users_clean = users.copy() 
users_clean.head(20)

,user_id,user_name,gender,age,city,state,preferred_language,signup_date,device_preference,user_status
0,100001,Priya Sharma,Female,19,Mumbai,Maharashtra,Hindi,2020-01-02,TV,Active
1,100002,Amit Reddy,Other,20,Bangalore,Karnataka,English,2020-01-03,Web,Inactive
2,100003,Sunita Rao,male,21,Chennai,Tamil Nadu,Tamil,2020-01-04,Tablet,Blocked
3,100004,Ravi Singh,FEMALE,22,Delhi,Delhi,Kannada,2020-01-05,mobile,Active
4,100005,Lakshmi Nair,M,23,Pune,Andhra Pradesh,Malayalam,2020-01-06,WEB,Active
5,100006,Vijay Pillai,Female,24,Kolkata,West Bengal,Telugu,2020-01-07,Mobile,Active
6,100007,Meena Verma,Male,25,Ahmedabad,Gujarat,Hindi,2020-01-08,TV,Inactive
7,100008,Sanjay Gupta,Female,26,Jaipur,Rajasthan,English,2020-01-09,Web,Blocked
8,100009,Kavitha Patel,Other,27,Lucknow,Uttar Pradesh,Tamil,2020-01-10,Tablet,Active
9,100010,Arun Iyer,male,28,Hydrabad,Kerala,Kannada,2020-01-11,mobile,Active
10,100011,Deepa Menon,FEMALE,29,Bangaluru,None,Malayalam,2020-01-12,WEB,Active
11,100012,Kiran Joshi,M,30,Chenai,Telangana,Telugu,2020-01-13,Mobile,Inactive
12,100013,Anita Das,Female,31,Mumabi,Maharashtra,None,2020-01-14,TV,Blocked
13,100014,Suresh Bhat,Male,32,Delhii,Karnataka,English,2020-01-15,Web,Active
14,100015,Pooja Chowdhury,Female,33,Vizag,Tamil Nadu,Tamil,2020-01-16,Tablet,Active
15,100016,Rahul Naidu,Other,34,Warangal,Delhi,Kannada,2020-01-17,mobile,Active
16,100017,Nisha Hegde,male,35,Vijayawada,Andhra Pradesh,Malayalam,2020-01-18,WEB,Inactive
17,100018,Mahesh Desai,FEMALE,36,Coimbatore,West Bengal,Telugu,2020-01-19,Mobile,Blocked
18,100019,Rekha Mishra,M,37,Kochi,Gujarat,Hindi,2020-01-20,TV,Active
19,100020,Arjun Kumar,Female,38,Hyderabad,Rajasthan,English,2020-01-21,Web,Active

In [8]:
users_clean.columns

Index(['user_id', 'user_name', 'gender', 'age', 'city', 'state',
       'preferred_language', 'signup_date', 'device_preference',
       'user_status'],
      dtype='object')

In [9]:
users_clean.dtypes

user_id                int64
user_name             object
gender                object
age                    int64
city                  object
state                 object
preferred_language    object
signup_date           object
device_preference     object
user_status           object
dtype: object

In [10]:
users_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   user_id             500000 non-null  int64
 1   user_name           489362 non-null  object
 2   gender              500000 non-null  object
 3   age                 500000 non-null  int64
 4   city                500000 non-null  object
 5   state               454546 non-null  object
 6   preferred_language  461539 non-null  object
 7   signup_date         500000 non-null  object
 8   device_preference   500000 non-null  object
 9   user_status         500000 non-null  object
dtypes: int64(2), object(8)
memory usage: 38.1+ MB

In [11]:
users_clean.isna().sum()

user_id                   0
user_name             10638
gender                    0
age                       0
city                      0
state                 45454
preferred_language    38461
signup_date               0
device_preference         0
user_status               0
dtype: int64

In [12]:
users_clean.isna().sum()

user_id                   0
user_name             10638
gender                    0
age                       0
city                      0
state                 45454
preferred_language    38461
signup_date               0
device_preference         0
user_status               0
dtype: int64

In [13]:
users_clean.duplicated().sum()

np.int64(0)

In [14]:
data = ['user_id',
'user_name',
'gender',
'age',
'city',
'state',
'preferred_language',
'signup_date',
'device_preference',
'user_status']
for i in data:
    print(f"{i} \n {users_clean[i].unique() }\n")

user_id
 [100001 100002 100003 ... 599998 599999 600000]

user_name
 ['Priya Sharma' 'Amit Reddy' 'Sunita Rao' 'Ravi Singh' 'Lakshmi Nair'
 'Vijay Pillai' 'Meena Verma' 'Sanjay Gupta' 'Kavitha Patel' 'Arun Iyer'
 'Deepa Menon' 'Kiran Joshi' 'Anita Das' 'Suresh Bhat' 'Pooja Chowdhury'
 'Rahul Naidu' 'Nisha Hegde' 'Mahesh Desai' 'Rekha Mishra' 'Arjun Kumar'
 'Divya Sharma' 'Naveen Reddy' 'Swathi Rao' 'Rajesh Singh' 'Sneha Nair'
 'Vinod Pillai' 'Usha Verma' 'Prasad Gupta' 'Suma Patel' 'Raj Iyer'
 'Priya Menon' 'Amit Joshi' 'Sunita Das' 'Ravi Bhat' 'Lakshmi Chowdhury'
 'Vijay Naidu' 'Meena Hegde' 'Sanjay Desai' 'Kavitha Mishra' 'Arun Kumar'
 'Deepa Sharma' 'Kiran Reddy' 'Anita Rao' 'Suresh Singh' 'Pooja Nair'
 'Rahul Pillai' None 'Mahesh Gupta' 'Rekha Patel' 'Arjun Iyer'
 'Divya Menon' 'Naveen Joshi' 'Swathi Das' 'Rajesh Bhat' 'Sneha Chowdhury'
 'Vinod Naidu' 'Usha Hegde' 'Prasad Desai' 'Suma Mishra' 'Raj Kumar'
 'Nisha Verma']

gender
 ['Female' 'Other' 'male' 'FEMALE' 'M' 'Male']

age
 [19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42
 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66
 67 68 69 70 18]

city
 ['Mumbai' 'Bangalore' 'Chennai' 'Delhi' 'Pune' 'Kolkata' 'Ahmedabad'
 'Jaipur' 'Lucknow' 'Hydrabad' 'Bangaluru' 'Chenai' 'Mumabi' 'Delhii'
 'Vizag' 'Warangal' 'Vijayawada' 'Coimbatore' 'Kochi' 'Hyderabad']

state
 ['Maharashtra' 'Karnataka' 'Tamil Nadu' 'Delhi' 'Andhra Pradesh'
 'West Bengal' 'Gujarat' 'Rajasthan' 'Uttar Pradesh' 'Kerala' None
 'Telangana' 'Punjab']

preferred_language
 ['Hindi' 'English' 'Tamil' 'Kannada' 'Malayalam' 'Telugu' None]

signup_date
 [datetime.date(2020, 1, 2) datetime.date(2020, 1, 3)
 datetime.date(2020, 1, 4) ... datetime.date(2024, 12, 29)
 datetime.date(2024, 12, 30) datetime.date(2020, 1, 1)]

device_preference
 ['TV' 'Web' 'Tablet' 'mobile' 'WEB' 'Mobile']

user_status
 ['Active' 'Inactive' 'Blocked']

In [15]:
users_clean.head()

,user_id,user_name,gender,age,city,state,preferred_language,signup_date,device_preference,user_status
0,100001,Priya Sharma,Female,19,Mumbai,Maharashtra,Hindi,2020-01-02,TV,Active
1,100002,Amit Reddy,Other,20,Bangalore,Karnataka,English,2020-01-03,Web,Inactive
2,100003,Sunita Rao,male,21,Chennai,Tamil Nadu,Tamil,2020-01-04,Tablet,Blocked
3,100004,Ravi Singh,FEMALE,22,Delhi,Delhi,Kannada,2020-01-05,mobile,Active
4,100005,Lakshmi Nair,M,23,Pune,Andhra Pradesh,Malayalam,2020-01-06,WEB,Active

# Data cleaning

### Data Type Change 'signup_date' column

In [16]:
users_clean['signup_date'] = pd.to_datetime(users_clean['signup_date'],errors = 'coerce')
print(users_clean['signup_date'].dtype)

datetime64[ns]

### Standerised String Column

### users_name column

In [17]:
users_clean['user_name'] = users_clean['user_name'].str.strip().str.title()

In [18]:
users_clean['user_name'] = users_clean['user_name'].fillna("Unknown")
print(users_clean['user_name'].unique())

['Priya Sharma' 'Amit Reddy' 'Sunita Rao' 'Ravi Singh' 'Lakshmi Nair'
 'Vijay Pillai' 'Meena Verma' 'Sanjay Gupta' 'Kavitha Patel' 'Arun Iyer'
 'Deepa Menon' 'Kiran Joshi' 'Anita Das' 'Suresh Bhat' 'Pooja Chowdhury'
 'Rahul Naidu' 'Nisha Hegde' 'Mahesh Desai' 'Rekha Mishra' 'Arjun Kumar'
 'Divya Sharma' 'Naveen Reddy' 'Swathi Rao' 'Rajesh Singh' 'Sneha Nair'
 'Vinod Pillai' 'Usha Verma' 'Prasad Gupta' 'Suma Patel' 'Raj Iyer'
 'Priya Menon' 'Amit Joshi' 'Sunita Das' 'Ravi Bhat' 'Lakshmi Chowdhury'
 'Vijay Naidu' 'Meena Hegde' 'Sanjay Desai' 'Kavitha Mishra' 'Arun Kumar'
 'Deepa Sharma' 'Kiran Reddy' 'Anita Rao' 'Suresh Singh' 'Pooja Nair'
 'Rahul Pillai' 'Unknown' 'Mahesh Gupta' 'Rekha Patel' 'Arjun Iyer'
 'Divya Menon' 'Naveen Joshi' 'Swathi Das' 'Rajesh Bhat' 'Sneha Chowdhury'
 'Vinod Naidu' 'Usha Hegde' 'Prasad Desai' 'Suma Mishra' 'Raj Kumar'
 'Nisha Verma']

### gender column

In [19]:
users_clean['gender'] = users_clean['gender'].str.strip().str.title()
users_clean['gender'] = users_clean['gender'].replace('M','Male')
print(users_clean['gender'].unique())

['Female' 'Other' 'Male']

In [20]:
male_names = [
    'Amit', 'Ravi', 'Vijay', 'Sanjay', 'Arun',
    'Kiran', 'Suresh', 'Rahul', 'Mahesh',
    'Arjun', 'Naveen', 'Rajesh', 'Vinod',
    'Prasad', 'Raj'
]

female_names = [
    'Priya', 'Sunita', 'Lakshmi', 'Meena',
    'Kavitha', 'Deepa', 'Anita', 'Pooja',
    'Nisha', 'Rekha', 'Divya', 'Swathi',
    'Sneha', 'Usha', 'Suma'
]

In [21]:
def assign_gender(name):

    first_name = name.split()[0]

    if first_name in male_names:
        return 'Male'

    elif first_name in female_names:
        return 'Female'

    else:
        return 'Unknown'

In [22]:
users_clean['gender'] = users_clean[
    'user_name'
].apply(assign_gender)

In [23]:
users_clean[['user_name','gender']].head(20)

          user_name  gender
0      Priya Sharma  Female
1        Amit Reddy    Male
2        Sunita Rao  Female
3        Ravi Singh    Male
4      Lakshmi Nair  Female
5      Vijay Pillai    Male
6       Meena Verma  Female
7      Sanjay Gupta    Male
8     Kavitha Patel  Female
9         Arun Iyer    Male
10      Deepa Menon  Female
11      Kiran Joshi    Male
12        Anita Das  Female
13      Suresh Bhat    Male
14  Pooja Chowdhury  Female
15      Rahul Naidu    Male
16      Nisha Hegde  Female
17     Mahesh Desai    Male
18     Rekha Mishra  Female
19      Arjun Kumar    Male

In [24]:
users_clean['gender'].unique()

array(['Female', 'Male', 'Unknown'], dtype=object)

### 'city' column

In [25]:
users_clean['city'] = users_clean['city'].str.strip().str.title()
users_clean['city'] = users_clean['city'].replace({'Mumabi':'Mumbai','Bangalore':'Bengaluru','Delhii':'Delhi','Bangaluru':'Bengaluru','Hydrabad':'Hyderabad','Chenai':'Chennai'})
print(users_clean['city'].unique())

['Mumbai' 'Bengaluru' 'Chennai' 'Delhi' 'Pune' 'Kolkata' 'Ahmedabad'
 'Jaipur' 'Lucknow' 'Hyderabad' 'Vizag' 'Warangal' 'Vijayawada'
 'Coimbatore' 'Kochi']

In [26]:
users_clean['city'].unique()

array(['Mumbai', 'Bengaluru', 'Chennai', 'Delhi', 'Pune', 'Kolkata',
       'Ahmedabad', 'Jaipur', 'Lucknow', 'Hyderabad', 'Vizag', 'Warangal',
       'Vijayawada', 'Coimbatore', 'Kochi'], dtype=object)

### 'state' column

In [261]:
users_clean['state'] = users_clean['state'].str.strip().str.title()
users_clean['state'] = users_clean['state'].fillna('Uttarakhand')
print(users_clean['state'].unique())
print(users_clean['state'].isna().sum())

['Maharashtra' 'Karnataka' 'Tamil Nadu' 'Delhi' 'Andhra Pradesh'
 'West Bengal' 'Gujarat' 'Rajasthan' 'Uttar Pradesh' 'Kerala'
 'Uttarakhand' 'Telangana' 'Punjab']
0

In [262]:
city_state_map = {
    'Mumbai': 'Maharashtra',
    'Pune': 'Maharashtra',

    'Bengaluru': 'Karnataka',

    'Chennai': 'Tamil Nadu',
    'Coimbatore': 'Tamil Nadu',

    'Delhi': 'Delhi',

    'Kolkata': 'West Bengal',

    'Ahmedabad': 'Gujarat',

    'Jaipur': 'Rajasthan',

    'Lucknow': 'Uttar Pradesh',

    'Hyderabad': 'Telangana',
    'Warangal': 'Telangana',

    'Vizag': 'Andhra Pradesh',
    'Vijayawada': 'Andhra Pradesh',

    'Kochi': 'Kerala'
}


users_clean['state'] = users_clean['state'].fillna(
    users_clean['city'].map(city_state_map)
)

In [263]:
users_clean['state'].isnull().sum()

np.int64(0)

### 'preferred_language' column

In [264]:
users_clean[['state','preferred_language']].head()

            state preferred_language
0     Maharashtra            Marathi
1       Karnataka            Kannada
2      Tamil Nadu              Tamil
3           Delhi              Hindi
4  Andhra Pradesh             Telugu

In [265]:
users_clean['preferred_language'].isnull().sum()

np.int64(0)

In [266]:
state_language_map = {
    'Maharashtra': 'Marathi',
    'Karnataka': 'Kannada',
    'Tamil Nadu': 'Tamil',
    'Kerala': 'Malayalam',
    'Gujarat': 'Gujarati',
    'West Bengal': 'Bengali',
    'Punjab': 'Punjabi',
    'Rajasthan': 'Hindi',
    'Delhi': 'Hindi',
    'Uttar Pradesh': 'Hindi',
    'Andhra Pradesh': 'Telugu',
    'Telangana': 'Telugu',
     'Uttarakhand' : 'Hindi'
}


users_clean['preferred_language'] = users_clean[
    'state'
].map(state_language_map)

In [267]:
users_clean['preferred_language'].isnull().sum()

np.int64(0)

### 'device_preference' column

In [268]:
users_clean['device_preference'] = users_clean['device_preference'].astype(str).str.strip().str.title()
print(users_clean['device_preference'].unique())

['Tv' 'Web' 'Tablet' 'Mobile']

### user_status

In [35]:
users_clean['user_status']  = users_clean['user_status'].astype(str).str.strip().str.title()
print(users_clean['user_status'].unique())

['Active' 'Inactive' 'Blocked']

### Cross Cheack

In [36]:
users_clean.dtypes

user_id                        int64
user_name                     object
gender                        object
age                            int64
city                          object
state                         object
preferred_language            object
signup_date           datetime64[ns]
device_preference             object
user_status                   object
dtype: object

In [37]:
users_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   user_id             500000 non-null  int64
 1   user_name           500000 non-null  object
 2   gender              500000 non-null  object
 3   age                 500000 non-null  int64
 4   city                500000 non-null  object
 5   state               500000 non-null  object
 6   preferred_language  500000 non-null  object
 7   signup_date         500000 non-null  datetime64[ns]
 8   device_preference   500000 non-null  object
 9   user_status         500000 non-null  object
dtypes: datetime64[ns](1), int64(2), object(7)
memory usage: 38.1+ MB

In [38]:
users_clean.isna().sum()

user_id               0
user_name             0
gender                0
age                   0
city                  0
state                 0
preferred_language    0
signup_date           0
device_preference     0
user_status           0
dtype: int64

In [39]:
users_clean.duplicated().sum()

np.int64(0)

### Clean Table Save In CSV File

In [40]:
users_clean.to_csv(r"C:\Users\DELL\Downloads\Movie_Ott_Project_File\Clean_file Csv\users_clean.csv",index = False)

# Subscriptions Table

# Data Understanding

In [41]:
sub_clean = subscriptions.copy()
sub_clean.head()

,subscription_id,user_id,plan_type,plan_price,subscription_start_date,subscription_end_date,auto_renewal_flag,subscription_status,cancellation_reason,payment_status
0,7000001,100002,Quarterly,299.0,2021-01-02,2021-04-02,No,Active,None,Success
1,7000002,100003,Annual,499.0,2021-01-03,2022-01-03,yes,Cancelled,None,Failed
2,7000003,100004,Family,699.0,2021-01-04,2021-02-03,Yes,Expired,Found Better Platform,Refunded
3,7000004,100005,Premium,999.0,2021-01-05,2021-04-05,No,Paused,None,success
4,7000005,100006,monthly,149.0,2021-01-06,2022-01-06,yes,Active,None,Success

In [42]:
sub_clean.shape

(800000, 10)

In [43]:
sub_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   subscription_id          800000 non-null  int64
 1   user_id                  800000 non-null  int64
 2   plan_type                800000 non-null  object
 3   plan_price               800000 non-null  float64
 4   subscription_start_date  800000 non-null  object
 5   subscription_end_date    800000 non-null  object
 6   auto_renewal_flag        738462 non-null  object
 7   subscription_status      800000 non-null  object
 8   cancellation_reason      160000 non-null  object
 9   payment_status           800000 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 61.0+ MB

In [44]:
sub_clean.isna().sum()

subscription_id                 0
user_id                         0
plan_type                       0
plan_price                      0
subscription_start_date         0
subscription_end_date           0
auto_renewal_flag           61538
subscription_status             0
cancellation_reason        640000
payment_status                  0
dtype: int64

In [45]:
column =['subscription_id','user_id','plan_type','plan_price','subscription_start_date','subscription_end_date',
         'auto_renewal_flag','subscription_status','cancellation_reason','payment_status']

for col in column:
    print(f"{col} \n {sub_clean[col].unique()}\n")

subscription_id
 [7000001 7000002 7000003 ... 7799998 7799999 7800000]

user_id
 [100002 100003 100004 ... 599999 600000 100001]

plan_type
 ['Quarterly' 'Annual' 'Family' 'Premium' 'monthly' 'ANNUAL' 'Monthly']

plan_price
 [299. 499. 699. 999. 149.]

subscription_start_date
 [datetime.date(2021, 1, 2) datetime.date(2021, 1, 3)
 datetime.date(2021, 1, 4) ... datetime.date(2024, 12, 30)
 datetime.date(2024, 12, 31) datetime.date(2021, 1, 1)]

subscription_end_date
 [datetime.date(2021, 4, 2) datetime.date(2022, 1, 3)
 datetime.date(2021, 2, 3) ... datetime.date(2025, 1, 28)
 datetime.date(2025, 12, 31) datetime.date(2021, 1, 31)]

auto_renewal_flag
 ['No' 'yes' 'Yes' None]

subscription_status
 ['Active' 'Cancelled' 'Expired' 'Paused']

cancellation_reason
 [None 'Found Better Platform']

payment_status
 ['Success' 'Failed' 'Refunded' 'success']

In [46]:
sub_clean.head()

,subscription_id,user_id,plan_type,plan_price,subscription_start_date,subscription_end_date,auto_renewal_flag,subscription_status,cancellation_reason,payment_status
0,7000001,100002,Quarterly,299.0,2021-01-02,2021-04-02,No,Active,None,Success
1,7000002,100003,Annual,499.0,2021-01-03,2022-01-03,yes,Cancelled,None,Failed
2,7000003,100004,Family,699.0,2021-01-04,2021-02-03,Yes,Expired,Found Better Platform,Refunded
3,7000004,100005,Premium,999.0,2021-01-05,2021-04-05,No,Paused,None,success
4,7000005,100006,monthly,149.0,2021-01-06,2022-01-06,yes,Active,None,Success

## Data Cleaning

###  user_id **

In [47]:
sub_clean[sub_clean['user_id']<0]

Empty DataFrame
Columns: [subscription_id, user_id, plan_type, plan_price, subscription_start_date, subscription_end_date, auto_renewal_flag, subscription_status, cancellation_reason, payment_status]
Index: []

###  plan_type column

In [48]:
sub_clean['plan_type'].unique()

array(['Quarterly', 'Annual', 'Family', 'Premium', 'monthly', 'ANNUAL',
       'Monthly'], dtype=object)

In [49]:
sub_clean['plan_type'] = sub_clean['plan_type'].astype(str).str.strip().str.title()
sub_clean['plan_type'].unique()

array(['Quarterly', 'Annual', 'Family', 'Premium', 'Monthly'],
      dtype=object)

### 'plan_price'

In [50]:
print(sub_clean['plan_price'].value_counts())

plan_price
299.0    160000
499.0    160000
699.0    160000
999.0    160000
149.0    160000
Name: count, dtype: int64

### date column data Type change

In [51]:
sub_clean['subscription_start_date'] = pd.to_datetime(sub_clean['subscription_start_date'],errors = 'coerce')
sub_clean['subscription_end_date'] = pd.to_datetime(sub_clean['subscription_end_date'],errors = 'coerce')

In [52]:
print(sub_clean['subscription_start_date'].dtype)
print(sub_clean['subscription_end_date'].dtype)

datetime64[ns]
datetime64[ns]

### 'auto_renewal_flag' column

In [53]:
sub_clean.columns

Index(['subscription_id', 'user_id', 'plan_type', 'plan_price',
       'subscription_start_date', 'subscription_end_date', 'auto_renewal_flag',
       'subscription_status', 'cancellation_reason', 'payment_status'],
      dtype='object')

### In this column null value fill  --- > 'No' <--- mode  value get 'yes' but did not fill

In [54]:
sub_clean['auto_renewal_flag'] = sub_clean['auto_renewal_flag'].astype(str).str.strip().str.title()
sub_clean['auto_renewal_flag'] = sub_clean['auto_renewal_flag'].replace('None','No')

In [55]:
sub_clean['auto_renewal_flag'].unique()

array(['No', 'Yes'], dtype=object)

### 'subscription_status'

In [56]:
sub_clean['subscription_status'] = sub_clean['subscription_status'].astype(str).str.strip().str.title()
sub_clean['subscription_status'].unique()

array(['Active', 'Cancelled', 'Expired', 'Paused'], dtype=object)

### 'cancellation_reason'

### 'cancellation_reason' in this column i filled 'Unknown' value

In [57]:
sub_clean['cancellation_reason']  = sub_clean['cancellation_reason'].str.strip().str.title()
sub_clean['cancellation_reason'] = sub_clean['cancellation_reason'].fillna("No Reason")

In [58]:
sub_clean['cancellation_reason'].unique()

array(['No Reason', 'Found Better Platform'], dtype=object)

## 'payment_status'

In [59]:
sub_clean['payment_status'] = sub_clean['payment_status'].str.strip().str.title()
print(sub_clean['payment_status'].unique())

['Success' 'Failed' 'Refunded']

## Cross Cheack

In [60]:
sub_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   subscription_id          800000 non-null  int64
 1   user_id                  800000 non-null  int64
 2   plan_type                800000 non-null  object
 3   plan_price               800000 non-null  float64
 4   subscription_start_date  800000 non-null  datetime64[ns]
 5   subscription_end_date    800000 non-null  datetime64[ns]
 6   auto_renewal_flag        800000 non-null  object
 7   subscription_status      800000 non-null  object
 8   cancellation_reason      800000 non-null  object
 9   payment_status           800000 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(5)
memory usage: 61.0+ MB

In [61]:
sub_clean.isna().sum()

subscription_id            0
user_id                    0
plan_type                  0
plan_price                 0
subscription_start_date    0
subscription_end_date      0
auto_renewal_flag          0
subscription_status        0
cancellation_reason        0
payment_status             0
dtype: int64

In [62]:
sub_clean.duplicated().sum()

np.int64(0)

### Clean Table Save In CSV File

In [63]:
sub_clean.to_csv(r"C:\Users\DELL\Downloads\Movie_Ott_Project_File\Clean_file Csv\subscriptions_clean.csv",index = False)

## Movies_Series Table

## Data Understanding

In [64]:
movies_series_clean = movie_series.copy()
movies_series_clean.head()

,content_id,title,content_type,genre,language,release_date,duration_minutes,content_rating,production_cost,content_status
0,5001,Golden Legacy,Series,Drama,Hindi,2018-01-02,21,1.1,500001.0,Removed
1,5002,Silent Empire,Documentary,Comedy,English,2018-01-03,22,1.2,500002.0,Upcoming
2,5003,Rising Dawn,Sports,Thriller,Tamil,2018-01-04,23,1.3,500003.0,available
3,5004,Broken Night,Movie,Romance,Kannada,2018-01-05,24,1.4,500004.0,Available
4,5005,Lost Warriors,Movie,action,Malayalam,2018-01-06,25,1.5,500005.0,Removed

In [65]:
movies_series_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   content_id        5000 non-null   int64
 1   title             5000 non-null   object
 2   content_type      5000 non-null   object
 3   genre             5000 non-null   object
 4   language          4706 non-null   object
 5   release_date      5000 non-null   object
 6   duration_minutes  5000 non-null   int64
 7   content_rating    5000 non-null   float64
 8   production_cost   5000 non-null   float64
 9   content_status    5000 non-null   object
dtypes: float64(2), int64(2), object(6)
memory usage: 390.8+ KB

In [66]:
movies_series_clean.isna().sum()

content_id            0
title                 0
content_type          0
genre                 0
language            294
release_date          0
duration_minutes      0
content_rating        0
production_cost       0
content_status        0
dtype: int64

In [67]:
column = ['content_id','title','content_type','genre','language','release_date','duration_minutes','content_rating','production_cost','content_status']
for col in column:
    print(f"{col} \n{movies_series_clean[col].unique()} \n ")

content_id
[ 5001  5002  5003 ...  9998  9999 10000]

title
['Golden Legacy' 'Silent Empire' 'Rising Dawn' 'Broken Night'
 'Lost Warriors' 'Hidden Destiny' 'Sacred Journey' 'Wild Path'
 'Iron Truth' 'Shadow Promise' 'Burning Secrets' 'Last Chronicles'
 'First Tales' 'Final Dreams' 'Blue Valley' 'Red Mountain' 'Black River'
 'White Sky' 'Crimson Ocean' 'Storm Horizon' 'Fire Legacy' 'Ice Empire'
 'Steel Dawn' 'Thunder Night' 'Dark Warriors' 'Golden Destiny'
 'Silent Journey' 'Rising Path' 'Broken Truth' 'Lost Promise'
 'Hidden Secrets' 'Sacred Chronicles' 'Wild Tales' 'Iron Dreams'
 'Shadow Valley' 'Burning Mountain' 'Last River' 'First Sky' 'Final Ocean'
 'Blue Horizon' 'Red Legacy' 'Black Empire' 'White Dawn' 'Crimson Night'
 'Storm Warriors' 'Fire Destiny' 'Ice Journey' 'Steel Path'
 'Thunder Truth' 'Dark Promise' 'Golden Secrets' 'Silent Chronicles'
 'Rising Tales' 'Broken Dreams' 'Lost Valley' 'Hidden Mountain'
 'Sacred River' 'Wild Sky' 'Iron Ocean' 'Shadow Horizon' 'Burning Legacy'
 'Last Empire' 'First Dawn' 'Final Night' 'Blue Warriors' 'Red Destiny'
 'Black Journey' 'White Path' 'Crimson Truth' 'Storm Promise'
 'Fire Secrets' 'Ice Chronicles' 'Steel Tales' 'Thunder Dreams'
 'Dark Valley' 'Golden Mountain' 'Silent River' 'Rising Sky'
 'Broken Ocean' 'Lost Horizon' 'Hidden Legacy' 'Sacred Empire' 'Wild Dawn'
 'Iron Night' 'Shadow Warriors' 'Burning Destiny' 'Last Journey'
 'First Path' 'Final Truth' 'Blue Promise' 'Red Secrets'
 'Black Chronicles' 'White Tales' 'Crimson Dreams' 'Storm Valley'
 'Fire Mountain' 'Ice River' 'Steel Sky' 'Thunder Ocean' 'Dark Horizon']

content_type
['Series' 'Documentary' 'Sports' 'Movie']

genre
['Drama' 'Comedy' 'Thriller' 'Romance' 'action' 'DRAMA' 'Horror' 'Sci-Fi'
 'Action']

language
['Hindi' 'English' 'Tamil' 'Kannada' 'Malayalam' 'Telugu' None]

release_date
[datetime.date(2018, 1, 2) datetime.date(2018, 1, 3)
 datetime.date(2018, 1, 4) ... datetime.date(2024, 12, 30)
 datetime.date(2024, 12, 31) datetime.date(2018, 1, 1)]

duration_minutes
[ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110
 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128
 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146
 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164
 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182
 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200
 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218
 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236
 237 238 239 240  20]

content_rating
[1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8
 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6
 4.7 4.8 4.9 1. ]

production_cost
[500001. 500002. 500003. ... 504998. 504999. 505000.]

content_status
['Removed' 'Upcoming' 'available' 'Available']

# Data Cleaning

### 'title'

In [68]:
movies_series_clean['title'] = movies_series_clean['title'].str.strip().str.title()
print(movies_series_clean['title'].unique())

['Golden Legacy' 'Silent Empire' 'Rising Dawn' 'Broken Night'
 'Lost Warriors' 'Hidden Destiny' 'Sacred Journey' 'Wild Path'
 'Iron Truth' 'Shadow Promise' 'Burning Secrets' 'Last Chronicles'
 'First Tales' 'Final Dreams' 'Blue Valley' 'Red Mountain' 'Black River'
 'White Sky' 'Crimson Ocean' 'Storm Horizon' 'Fire Legacy' 'Ice Empire'
 'Steel Dawn' 'Thunder Night' 'Dark Warriors' 'Golden Destiny'
 'Silent Journey' 'Rising Path' 'Broken Truth' 'Lost Promise'
 'Hidden Secrets' 'Sacred Chronicles' 'Wild Tales' 'Iron Dreams'
 'Shadow Valley' 'Burning Mountain' 'Last River' 'First Sky' 'Final Ocean'
 'Blue Horizon' 'Red Legacy' 'Black Empire' 'White Dawn' 'Crimson Night'
 'Storm Warriors' 'Fire Destiny' 'Ice Journey' 'Steel Path'
 'Thunder Truth' 'Dark Promise' 'Golden Secrets' 'Silent Chronicles'
 'Rising Tales' 'Broken Dreams' 'Lost Valley' 'Hidden Mountain'
 'Sacred River' 'Wild Sky' 'Iron Ocean' 'Shadow Horizon' 'Burning Legacy'
 'Last Empire' 'First Dawn' 'Final Night' 'Blue Warriors' 'Red Destiny'
 'Black Journey' 'White Path' 'Crimson Truth' 'Storm Promise'
 'Fire Secrets' 'Ice Chronicles' 'Steel Tales' 'Thunder Dreams'
 'Dark Valley' 'Golden Mountain' 'Silent River' 'Rising Sky'
 'Broken Ocean' 'Lost Horizon' 'Hidden Legacy' 'Sacred Empire' 'Wild Dawn'
 'Iron Night' 'Shadow Warriors' 'Burning Destiny' 'Last Journey'
 'First Path' 'Final Truth' 'Blue Promise' 'Red Secrets'
 'Black Chronicles' 'White Tales' 'Crimson Dreams' 'Storm Valley'
 'Fire Mountain' 'Ice River' 'Steel Sky' 'Thunder Ocean' 'Dark Horizon']

### 'content_type'

In [69]:
movies_series_clean['content_type'] = movies_series_clean['content_type'].str.strip().str.title()
movies_series_clean['content_type'].unique()

array(['Series', 'Documentary', 'Sports', 'Movie'], dtype=object)

### genre

In [70]:
movies_series_clean['genre'] = movies_series_clean['genre'].str.strip().str.title()

In [71]:
movies_series_clean['genre'].unique()
movies_series_clean['genre'].value_counts()

genre
Drama       1000
Comedy      1000
Action      1000
Thriller     500
Romance      500
Horror       500
Sci-Fi       500
Name: count, dtype: int64

### language

### unknown value filled with

In [72]:
movies_series_clean.head(15)

,content_id,title,content_type,genre,language,release_date,duration_minutes,content_rating,production_cost,content_status
0,5001,Golden Legacy,Series,Drama,Hindi,2018-01-02,21,1.1,500001.0,Removed
1,5002,Silent Empire,Documentary,Comedy,English,2018-01-03,22,1.2,500002.0,Upcoming
2,5003,Rising Dawn,Sports,Thriller,Tamil,2018-01-04,23,1.3,500003.0,available
3,5004,Broken Night,Movie,Romance,Kannada,2018-01-05,24,1.4,500004.0,Available
4,5005,Lost Warriors,Movie,Action,Malayalam,2018-01-06,25,1.5,500005.0,Removed
5,5006,Hidden Destiny,Series,Drama,Telugu,2018-01-07,26,1.6,500006.0,Upcoming
6,5007,Sacred Journey,Documentary,Comedy,Hindi,2018-01-08,27,1.7,500007.0,available
7,5008,Wild Path,Sports,Horror,English,2018-01-09,28,1.8,500008.0,Available
8,5009,Iron Truth,Movie,Sci-Fi,Tamil,2018-01-10,29,1.9,500009.0,Removed
9,5010,Shadow Promise,Movie,Action,Kannada,2018-01-11,30,2.0,500010.0,Upcoming
10,5011,Burning Secrets,Series,Drama,Malayalam,2018-01-12,31,2.1,500011.0,available
11,5012,Last Chronicles,Documentary,Comedy,Telugu,2018-01-13,32,2.2,500012.0,Available
12,5013,First Tales,Sports,Thriller,Hindi,2018-01-14,33,2.3,500013.0,Removed
13,5014,Final Dreams,Movie,Romance,English,2018-01-15,34,2.4,500014.0,Upcoming
14,5015,Blue Valley,Movie,Action,Tamil,2018-01-16,35,2.5,500015.0,available

In [73]:
lang_mode = movies_series_clean['language'].mode()[0]

In [74]:
movies_series_clean['language'] = movies_series_clean['language'].fillna(lang_mode).str.strip().str.title()

In [75]:
movies_series_clean['language'].unique()

array(['Hindi', 'English', 'Tamil', 'Kannada', 'Malayalam', 'Telugu'],
      dtype=object)

## 'release_date'

In [76]:
movies_series_clean['release_date'] = pd.to_datetime(movies_series_clean['release_date'],errors = 'coerce')
movies_series_clean['release_date'].value_counts()

release_date
2024-09-09    2
2024-09-08    2
2024-09-07    2
2024-09-06    2
2024-09-05    2
             ..
2024-12-28    1
2024-12-29    1
2024-12-30    1
2024-12-31    1
2018-01-01    1
Name: count, Length: 2557, dtype: int64

### 'duration_minutes'

In [77]:
movies_series_clean['duration_minutes'].value_counts()

duration_minutes
21     23
22     23
23     23
24     23
25     23
       ..
237    22
238    22
239    22
240    22
20     22
Name: count, Length: 221, dtype: int64

### content_rating

In [78]:
movies_series_clean['content_rating'].unique()

array([1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3,
       2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6,
       3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9,
       1. ])

In [79]:
movies_series_clean.describe()

,content_id,release_date,duration_minutes,content_rating,production_cost
count,5000.000000,5000,5000.000000,5000.000000,5000.000000
mean,7500.500000,2021-06-04 15:19:17.760000,128.882200,2.950000,502500.500000
min,5001.000000,2018-01-01 00:00:00,20.000000,1.000000,500001.000000
25%,6250.750000,2019-09-18 00:00:00,74.000000,1.975000,501250.750000
50%,7500.500000,2021-06-04 00:00:00,128.000000,2.950000,502500.500000
75%,8750.250000,2023-02-19 00:00:00,184.000000,3.925000,503750.250000
max,10000.000000,2024-12-31 00:00:00,240.000000,4.900000,505000.000000
std,1443.520003,NaN,63.610515,1.154455,1443.520003

### production_cost

In [80]:
movies_series_clean['production_cost'].value_counts()

production_cost
505000.0    1
500001.0    1
500002.0    1
500003.0    1
500004.0    1
           ..
500013.0    1
500012.0    1
500011.0    1
500010.0    1
500009.0    1
Name: count, Length: 5000, dtype: int64

### content_status

In [81]:
movies_series_clean['content_status'] = movies_series_clean['content_status'].str.strip().str.title()

In [82]:
movies_series_clean['content_status'].unique()

array(['Removed', 'Upcoming', 'Available'], dtype=object)

# Cross Cheack

In [83]:
movies_series_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   content_id        5000 non-null   int64
 1   title             5000 non-null   object
 2   content_type      5000 non-null   object
 3   genre             5000 non-null   object
 4   language          5000 non-null   object
 5   release_date      5000 non-null   datetime64[ns]
 6   duration_minutes  5000 non-null   int64
 7   content_rating    5000 non-null   float64
 8   production_cost   5000 non-null   float64
 9   content_status    5000 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(2), object(5)
memory usage: 390.8+ KB

In [84]:
movies_series_clean.head()

,content_id,title,content_type,genre,language,release_date,duration_minutes,content_rating,production_cost,content_status
0,5001,Golden Legacy,Series,Drama,Hindi,2018-01-02,21,1.1,500001.0,Removed
1,5002,Silent Empire,Documentary,Comedy,English,2018-01-03,22,1.2,500002.0,Upcoming
2,5003,Rising Dawn,Sports,Thriller,Tamil,2018-01-04,23,1.3,500003.0,Available
3,5004,Broken Night,Movie,Romance,Kannada,2018-01-05,24,1.4,500004.0,Available
4,5005,Lost Warriors,Movie,Action,Malayalam,2018-01-06,25,1.5,500005.0,Removed

In [85]:
movies_series_clean.isna().sum()

content_id          0
title               0
content_type        0
genre               0
language            0
release_date        0
duration_minutes    0
content_rating      0
production_cost     0
content_status      0
dtype: int64

In [86]:
movies_series_clean.duplicated().sum()

np.int64(0)

### Clean Table Save In CSV File

In [87]:
movies_series_clean.to_csv(r"C:\Users\DELL\Downloads\Movie_Ott_Project_File\Clean_file Csv\movies_series.csv",index = False)

# customer_complaints Table

# Data Understanding

In [88]:
customer_complaints_clean = customer_complaints.copy()
customer_complaints_clean.head(15)

,complaint_id,user_id,complaint_category,complaint_text,complaint_date,resolution_status,resolution_time_hours,customer_satisfaction_score
0,7500001,100002,Payment,Payment was deducted but subscription not acti...,2022-01-02 00:00:01,Resolved,2,2
1,7500002,100003,Content,Content I want is not available in my language.,2022-01-03 00:00:02,Escalated,3,3
2,7500003,100004,Subscription,Unable to cancel my subscription online.,2022-01-04 00:00:03,resolved,4,4
3,7500004,100005,Playback,App crashes frequently on mobile device.,2022-01-05 00:00:04,RESOLVED,5,5
4,7500005,100006,Payment,Subtitles are not synced with the video.,2022-01-06 00:00:05,Open,6,1
5,7500006,100007,Content,Audio quality drops during peak hours.,2022-01-07 00:00:06,Resolved,7,2
6,7500007,100008,Subscription,Wrong amount charged to my account.,2022-01-08 00:00:07,Escalated,8,3
7,7500008,100009,Playback,None,2022-01-09 00:00:08,resolved,9,4
8,7500009,100010,Payment,Payment was deducted but subscription not acti...,2022-01-10 00:00:09,RESOLVED,10,5
9,7500010,100011,Content,Content I want is not available in my language.,2022-01-11 00:00:10,Open,11,1
10,7500011,100012,Subscription,Unable to cancel my subscription online.,2022-01-12 00:00:11,Resolved,12,2
11,7500012,100013,Playback,App crashes frequently on mobile device.,2022-01-13 00:00:12,Escalated,13,3
12,7500013,100014,Payment,Subtitles are not synced with the video.,2022-01-14 00:00:13,resolved,14,4
13,7500014,100015,Content,Audio quality drops during peak hours.,2022-01-15 00:00:14,RESOLVED,15,5
14,7500015,100016,Subscription,Wrong amount charged to my account.,2022-01-16 00:00:15,Open,16,1

In [89]:
customer_complaints_clean.shape

(200000, 8)

In [90]:
customer_complaints_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   complaint_id                 200000 non-null  int64
 1   user_id                      200000 non-null  int64
 2   complaint_category           190477 non-null  object
 3   complaint_text               175000 non-null  object
 4   complaint_date               200000 non-null  datetime64[ns]
 5   resolution_status            200000 non-null  object
 6   resolution_time_hours        200000 non-null  int64
 7   customer_satisfaction_score  200000 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(3)
memory usage: 12.2+ MB

In [91]:
column = ['complaint_id','user_id','complaint_category','complaint_text','complaint_date','resolution_status',	
'resolution_time_hours','customer_satisfaction_score']
for col in column:
    print(f"{col} \n {customer_complaints_clean[col].unique()} \n")

complaint_id
 [7500001 7500002 7500003 ... 7699998 7699999 7700000]

user_id
 [100002 100003 100004 ... 299999 300000 300001]

complaint_category
 ['Payment' 'Content' 'Subscription' 'Playback' None]

complaint_text
 ['Payment was deducted but subscription not activated.'
 'Content I want is not available in my language.'
 'Unable to cancel my subscription online.'
 'App crashes frequently on mobile device.'
 'Subtitles are not synced with the video.'
 'Audio quality drops during peak hours.'
 'Wrong amount charged to my account.' None]

complaint_date
 <DatetimeArray>
['2022-01-02 00:00:01', '2022-01-03 00:00:02', '2022-01-04 00:00:03',
 '2022-01-05 00:00:04', '2022-01-06 00:00:05', '2022-01-07 00:00:06',
 '2022-01-08 00:00:07', '2022-01-09 00:00:08', '2022-01-10 00:00:09',
 '2022-01-11 00:00:10',
 ...
 '2023-06-04 07:33:11', '2023-06-05 07:33:12', '2023-06-06 07:33:13',
 '2023-06-07 07:33:14', '2023-06-08 07:33:15', '2023-06-09 07:33:16',
 '2023-06-10 07:33:17', '2023-06-11 07:33:18', '2023-06-12 07:33:19',
 '2023-06-13 07:33:20']
Length: 200000, dtype: datetime64[ns]

resolution_status
 ['Resolved' 'Escalated' 'resolved' 'RESOLVED' 'Open']

resolution_time_hours
 [  2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168   1]

customer_satisfaction_score
 [2 3 4 5 1]

In [92]:
customer_complaints_clean.isna().sum()

complaint_id                       0
user_id                            0
complaint_category              9523
complaint_text                 25000
complaint_date                     0
resolution_status                  0
resolution_time_hours              0
customer_satisfaction_score        0
dtype: int64

In [93]:
customer_complaints_clean[['complaint_category','complaint_text']]

       complaint_category                                     complaint_text
0                 Payment  Payment was deducted but subscription not acti...
1                 Content    Content I want is not available in my language.
2            Subscription           Unable to cancel my subscription online.
3                Playback           App crashes frequently on mobile device.
4                 Payment           Subtitles are not synced with the video.
...                   ...                                                ...
199995           Playback           App crashes frequently on mobile device.
199996            Payment           Subtitles are not synced with the video.
199997            Content             Audio quality drops during peak hours.
199998       Subscription                Wrong amount charged to my account.
199999           Playback                                               None

[200000 rows x 2 columns]

In [94]:
customer_complaints_clean[customer_complaints_clean['complaint_text'].isnull()]

,complaint_id,user_id,complaint_category,complaint_text,complaint_date,resolution_status,resolution_time_hours,customer_satisfaction_score
7,7500008,100009,Playback,None,2022-01-09 00:00:08,resolved,9,4
15,7500016,100017,Playback,None,2022-01-17 00:00:16,Resolved,17,2
23,7500024,100025,Playback,None,2022-01-25 00:00:24,RESOLVED,25,5
31,7500032,100033,Playback,None,2022-02-02 00:00:32,Escalated,33,3
39,7500040,100041,Playback,None,2022-02-10 00:00:40,Open,41,1
...,...,...,...,...,...,...,...,...
199967,7699968,299969,Playback,None,2023-05-12 07:32:48,resolved,49,4
199975,7699976,299977,Playback,None,2023-05-20 07:32:56,Resolved,57,2
199983,7699984,299985,Playback,None,2023-05-28 07:33:04,RESOLVED,65,5
199991,7699992,299993,Playback,None,2023-06-05 07:33:12,Escalated,73,3
199999,7700000,300001,Playback,None,2023-06-13 07:33:20,Open,81,1

# Data Cleaning

### complaint_id

In [95]:
customer_complaints_clean['complaint_id'].value_counts()

complaint_id
7699984    1
7699983    1
7699982    1
7699981    1
7699980    1
          ..
7500005    1
7500004    1
7500003    1
7500002    1
7500001    1
Name: count, Length: 200000, dtype: int64

### user_id **

In [96]:
customer_complaints_clean['user_id'].value_counts()

user_id
299985    1
299984    1
299983    1
299982    1
299981    1
         ..
100006    1
100005    1
100004    1
100003    1
100002    1
Name: count, Length: 200000, dtype: int64

In [97]:
customer_complaints_clean.isnull().sum()

complaint_id                       0
user_id                            0
complaint_category              9523
complaint_text                 25000
complaint_date                     0
resolution_status                  0
resolution_time_hours              0
customer_satisfaction_score        0
dtype: int64

### complaint_text

###  i filled null value "App Crashes Frequently On Mobile Device"

In [98]:
customer_complaints_clean.loc[
    customer_complaints_clean['complaint_category'] == 'Playback',
    'complaint_text'
] = 'App crashes frequently on mobile device.'

In [99]:
complaint_text_mode = customer_complaints_clean['complaint_text'].mode()[0]

In [100]:
customer_complaints_clean['complaint_text'] = customer_complaints_clean['complaint_text'].fillna(complaint_text_mode)

In [101]:
customer_complaints_clean['complaint_text'] = customer_complaints_clean['complaint_text'].str.strip().str.title()

In [102]:
customer_complaints_clean['complaint_text'].unique()

array(['Payment Was Deducted But Subscription Not Activated.',
       'Content I Want Is Not Available In My Language.',
       'Unable To Cancel My Subscription Online.',
       'App Crashes Frequently On Mobile Device.',
       'Subtitles Are Not Synced With The Video.',
       'Audio Quality Drops During Peak Hours.',
       'Wrong Amount Charged To My Account.'], dtype=object)

In [103]:
customer_complaints_clean[customer_complaints_clean['complaint_text'].isnull()]

Empty DataFrame
Columns: [complaint_id, user_id, complaint_category, complaint_text, complaint_date, resolution_status, resolution_time_hours, customer_satisfaction_score]
Index: []

In [104]:
customer_complaints_clean.isnull().sum()

complaint_id                      0
user_id                           0
complaint_category             9523
complaint_text                    0
complaint_date                    0
resolution_status                 0
resolution_time_hours             0
customer_satisfaction_score       0
dtype: int64

### complaint_category

In [105]:
complaint_category_map = {
    'Payment Was Deducted But Subscription Not Activated.': 'Payment',

    'Content I Want Is Not Available In My Language.': 'Content',

    'Unable To Cancel My Subscription Online.': 'Subscription',

    'App Crashes Frequently On Mobile Device.': 'Playback',

    'Subtitles Are Not Synced With The Video.': 'Payment',

    'Audio Quality Drops During Peak Hours.': 'Content',

    'Wrong Amount Charged To My Account.': 'Subscription'
}

In [106]:
customer_complaints_clean['complaint_category'] = (
    customer_complaints_clean['complaint_text'].map(
        complaint_category_map
    )
)

In [107]:

customer_complaints_clean['complaint_category'].unique()

array(['Payment', 'Content', 'Subscription', 'Playback'], dtype=object)

In [108]:
customer_complaints_clean.isnull().sum()

complaint_id                   0
user_id                        0
complaint_category             0
complaint_text                 0
complaint_date                 0
resolution_status              0
resolution_time_hours          0
customer_satisfaction_score    0
dtype: int64

In [109]:
customer_complaints_clean[['complaint_category','complaint_text']]

       complaint_category                                     complaint_text
0                 Payment  Payment Was Deducted But Subscription Not Acti...
1                 Content    Content I Want Is Not Available In My Language.
2            Subscription           Unable To Cancel My Subscription Online.
3                Playback           App Crashes Frequently On Mobile Device.
4                 Payment           Subtitles Are Not Synced With The Video.
...                   ...                                                ...
199995           Playback           App Crashes Frequently On Mobile Device.
199996            Payment           Subtitles Are Not Synced With The Video.
199997            Content             Audio Quality Drops During Peak Hours.
199998       Subscription                Wrong Amount Charged To My Account.
199999           Playback           App Crashes Frequently On Mobile Device.

[200000 rows x 2 columns]

In [110]:
customer_complaints_clean.isnull().sum()

complaint_id                   0
user_id                        0
complaint_category             0
complaint_text                 0
complaint_date                 0
resolution_status              0
resolution_time_hours          0
customer_satisfaction_score    0
dtype: int64

### resolution_status

In [111]:
customer_complaints_clean['resolution_status'] = customer_complaints_clean['resolution_status'].str.strip().str.title()
customer_complaints_clean['resolution_status'].unique()

array(['Resolved', 'Escalated', 'Open'], dtype=object)

### resolution_time_hours

In [112]:
print(customer_complaints_clean["resolution_time_hours"].unique())

[  2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19
  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168   1]

### customer_satisfaction_score

In [113]:
customer_complaints_clean['customer_satisfaction_score'].unique()

array([2, 3, 4, 5, 1])

# Cross Cheack

In [114]:
customer_complaints_clean.duplicated().sum()

np.int64(0)

In [115]:
customer_complaints_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   complaint_id                 200000 non-null  int64
 1   user_id                      200000 non-null  int64
 2   complaint_category           200000 non-null  object
 3   complaint_text               200000 non-null  object
 4   complaint_date               200000 non-null  datetime64[ns]
 5   resolution_status            200000 non-null  object
 6   resolution_time_hours        200000 non-null  int64
 7   customer_satisfaction_score  200000 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(3)
memory usage: 12.2+ MB

### Clean Table Save In CSV File

In [116]:
customer_complaints_clean.to_csv(r"C:\Users\DELL\Downloads\Movie_Ott_Project_File\Clean_file Csv\customer_complaints_clean.csv",index = False)

# Recommendations Table

In [117]:
recommendations_clean = recommendations.copy()
recommendations_clean.head()

,recommendation_id,user_id,content_id,recommendation_datetime,recommendation_type,impression_flag,clicked_flag,watched_after_click_flag,recommendation_rank
0,6000001,100002,5002,2023-01-02 00:00:01,Trending,1.0,0,0,2
1,6000002,100003,5003,2023-01-03 00:00:02,Personalized,1.0,0,0,3
2,6000003,100004,5004,2023-01-04 00:00:03,Top Picks,1.0,1,1,4
3,6000004,100005,5005,2023-01-05 00:00:04,Because You Watched,1.0,0,0,5
4,6000005,100006,5006,2023-01-06 00:00:05,Trending,1.0,0,0,6

## Data Understanding

In [119]:
recommendations_clean.head()

,recommendation_id,user_id,content_id,recommendation_datetime,recommendation_type,impression_flag,clicked_flag,watched_after_click_flag,recommendation_rank
0,6000001,100002,5002,2023-01-02 00:00:01,Trending,1.0,0,0,2
1,6000002,100003,5003,2023-01-03 00:00:02,Personalized,1.0,0,0,3
2,6000003,100004,5004,2023-01-04 00:00:03,Top Picks,1.0,1,1,4
3,6000004,100005,5005,2023-01-05 00:00:04,Because You Watched,1.0,0,0,5
4,6000005,100006,5006,2023-01-06 00:00:05,Trending,1.0,0,0,6

In [120]:
recommendations_clean.isna().sum()

recommendation_id                0
user_id                          0
content_id                       0
recommendation_datetime          0
recommendation_type         105262
impression_flag              64516
clicked_flag                     0
watched_after_click_flag         0
recommendation_rank              0
dtype: int64

In [121]:
recommendations_clean.duplicated().sum()

np.int64(0)

In [123]:
recommendations_clean.shape

(2000000, 9)

## Data Cleaning

#### recommendation_id

In [125]:
recommendations_clean[recommendations_clean['recommendation_id']<0]

Empty DataFrame
Columns: [recommendation_id, user_id, content_id, recommendation_datetime, recommendation_type, impression_flag, clicked_flag, watched_after_click_flag, recommendation_rank]
Index: []

#### user_id

In [126]:
recommendations_clean[recommendations_clean['user_id']<0]

Empty DataFrame
Columns: [recommendation_id, user_id, content_id, recommendation_datetime, recommendation_type, impression_flag, clicked_flag, watched_after_click_flag, recommendation_rank]
Index: []

#### content_id

In [127]:
recommendations_clean[recommendations_clean['content_id']<0]

Empty DataFrame
Columns: [recommendation_id, user_id, content_id, recommendation_datetime, recommendation_type, impression_flag, clicked_flag, watched_after_click_flag, recommendation_rank]
Index: []

#### recommendation_datetime

In [129]:
## Convert Datetime Column

recommendations_clean["recommendation_datetime"] = pd.to_datetime(
    recommendations_clean["recommendation_datetime"],
    errors="coerce"
)

In [131]:
recommendations_clean[recommendations_clean["recommendation_datetime"].isnull()]

Empty DataFrame
Columns: [recommendation_id, user_id, content_id, recommendation_datetime, recommendation_type, impression_flag, clicked_flag, watched_after_click_flag, recommendation_rank]
Index: []

#### recommendation_type

In [132]:
recommendations_clean['recommendation_type'] = recommendations_clean['recommendation_type'].fillna('Unknown')

In [133]:
recommendations_clean[recommendations_clean["recommendation_type"].isnull()]

Empty DataFrame
Columns: [recommendation_id, user_id, content_id, recommendation_datetime, recommendation_type, impression_flag, clicked_flag, watched_after_click_flag, recommendation_rank]
Index: []

#### impression_flag

In [134]:
recommendations_clean['impression_flag'] = recommendations_clean['impression_flag'].fillna(0)

In [135]:
recommendations_clean[recommendations_clean["impression_flag"].isnull()]

Empty DataFrame
Columns: [recommendation_id, user_id, content_id, recommendation_datetime, recommendation_type, impression_flag, clicked_flag, watched_after_click_flag, recommendation_rank]
Index: []

#### Duplicate Detection

In [136]:
recommendations_clean.duplicated().sum()

np.int64(0)

In [138]:
recommendations_clean.duplicated(
    subset=[
        "user_id",
        "content_id",
        "recommendation_datetime"
    ]
).sum()

np.int64(0)

#### Validate Rank Values

In [139]:
recommendations_clean["recommendation_rank"].describe()

count    2.000000e+06
mean     1.050000e+01
std      5.766283e+00
min      1.000000e+00
25%      5.750000e+00
50%      1.050000e+01
75%      1.525000e+01
max      2.000000e+01
Name: recommendation_rank, dtype: float64

#### Validate Binary Flags

In [140]:
binary_cols = ['impression_flag','clicked_flag','watched_after_click_flag']

for col in binary_cols:
    print(col, recommendations_clean[col].unique())

impression_flag [1. 0.]
clicked_flag [0 1]
watched_after_click_flag [0 1]

#### impression_flag Column dypes convert to Int64

In [142]:
recommendations_clean['impression_flag'] = (
    recommendations_clean['impression_flag']
    .astype('int64')
)

In [144]:
recommendations_clean.isnull().sum()

recommendation_id           0
user_id                     0
content_id                  0
recommendation_datetime     0
recommendation_type         0
impression_flag             0
clicked_flag                0
watched_after_click_flag    0
recommendation_rank         0
dtype: int64

### Saving the clean file

In [145]:
recommendations_clean.to_csv(r"C:\Users\DELL\Downloads\Movie_Ott_Project_File\Clean_file Csv\recommendation_clean1.csv",index = False)

# Watch History Table

In [146]:
watch_history_clean = watch_history.copy()

## Data Understanding

In [147]:
watch_history_clean.head()

,watch_id,user_id,content_id,watch_start_time,watch_end_time,watch_duration_minutes,device_type,completion_percentage,completion_flag,watch_city
0,9000001,100002,5002,2022-01-02 00:00:01,2022-01-02 00:00:02,2,TV,0.01,No,Mumbai
1,9000002,100003,5003,2022-01-03 00:00:02,2022-01-03 00:00:04,3,Web,0.02,No,Bangalore
2,9000003,100004,5004,2022-01-04 00:00:03,2022-01-04 00:00:06,4,Tablet,0.03,No,Chennai
3,9000004,100005,5005,2022-01-05 00:00:04,2022-01-05 00:00:08,5,mobile,0.04,No,Delhi
4,9000005,100006,5006,2022-01-06 00:00:05,2022-01-06 00:00:10,6,WEB,0.05,No,Pune

In [148]:
watch_history_clean.shape

(5000000, 10)

In [149]:
watch_history_clean.dtypes

watch_id                           int64
user_id                            int64
content_id                         int64
watch_start_time          datetime64[ns]
watch_end_time            datetime64[ns]
watch_duration_minutes             int64
device_type                       object
completion_percentage            float64
completion_flag                   object
watch_city                        object
dtype: object

In [150]:
watch_history_clean.isnull().sum()

watch_id                       0
user_id                        0
content_id                     0
watch_start_time               0
watch_end_time                 0
watch_duration_minutes         0
device_type                    0
completion_percentage          0
completion_flag           217391
watch_city                     0
dtype: int64

In [151]:
columns = ['device_type','completion_percentage', 'completion_flag', 'watch_city']

for col in columns:
    print(col,watch_history_clean[col].unique())

device_type ['TV' 'Web' 'Tablet' 'mobile' 'WEB' 'Mobile']
completion_percentage [1.000e-02 2.000e-02 3.000e-02 ... 9.999e+01 1.000e+02 0.000e+00]
completion_flag ['No' None 'Yes']
watch_city ['Mumbai' 'Bangalore' 'Chennai' 'Delhi' 'Pune' 'Kolkata' 'Hydrabad'
 'Bangaluru' 'Vizag' 'Warangal' 'Vijayawada' 'Jaipur' 'Lucknow' 'Kochi'
 'Hyderabad']

#### Standardization

In [152]:
watch_history_clean['device_type'] = (
    watch_history_clean['device_type'].astype(str)
    .str.strip()
    .str.title()
)

In [153]:
watch_history_clean['watch_city'] = (
    watch_history_clean['watch_city'].astype(str)
    .str.strip()
    .str.title()
)

In [154]:
watch_history_clean['watch_city'] = watch_history_clean['watch_city'].replace({'Hydrabad':'Hyderabad',
                                                                               'Bangalore': 'Bengaluru',
                                                                               'Bangaluru': 'Bengaluru',
                                                                            })

In [155]:
watch_history_clean.shape

(5000000, 10)

#### Convert date/time columns

In [156]:
for col in watch_history_clean.columns:
    if 'date' in col or 'time' in col:
        try:
            watch_history_clean[col] = pd.to_datetime(watch_history_clean[col], errors='coerce')
        except:
            pass

In [157]:
watch_history_clean.dtypes

watch_id                           int64
user_id                            int64
content_id                         int64
watch_start_time          datetime64[ns]
watch_end_time            datetime64[ns]
watch_duration_minutes             int64
device_type                       object
completion_percentage            float64
completion_flag                   object
watch_city                        object
dtype: object

#### Remove Duplicates

In [158]:
print('Before Removing Duplicates :' , watch_history_clean.shape)
watch_history_clean = watch_history_clean.drop_duplicates()
print('After Removing Duplicates :', watch_history_clean.shape)

Before Removing Duplicates : (5000000, 10)
After Removing Duplicates : (5000000, 10)

#### Handeling Missing value

In [159]:
watch_history_clean.isnull().sum()

watch_id                       0
user_id                        0
content_id                     0
watch_start_time               0
watch_end_time                 0
watch_duration_minutes         0
device_type                    0
completion_percentage          0
completion_flag           217391
watch_city                     0
dtype: int64

In [160]:
watch_history_clean['completion_flag'].unique()

array(['No', None, 'Yes'], dtype=object)

In [161]:
watch_history_clean['completion_flag'] = (
    watch_history_clean['completion_flag']
    .astype(str)
    .str.strip()
    .map({
        'yes': 1,
        'no': 0
    })
    .fillna(0)
    .astype('int64')
)

In [162]:
watch_history_clean.isnull().sum()

watch_id                  0
user_id                   0
content_id                0
watch_start_time          0
watch_end_time            0
watch_duration_minutes    0
device_type               0
completion_percentage     0
completion_flag           0
watch_city                0
dtype: int64

In [163]:
watch_history_clean.dtypes

watch_id                           int64
user_id                            int64
content_id                         int64
watch_start_time          datetime64[ns]
watch_end_time            datetime64[ns]
watch_duration_minutes             int64
device_type                       object
completion_percentage            float64
completion_flag                    int64
watch_city                        object
dtype: object

In [164]:
watch_history_clean.shape

(5000000, 10)

#### Saving the clean Table

In [165]:
watch_history_clean.to_csv(r"C:\Users\DELL\Downloads\Movie_Ott_Project_File\Clean_file Csv\watch_history_clean1.csv",index = False)

# Marketing campaign Table

In [170]:
marketing_campaigns_clean = marketing_campaigns.copy()

#### Data understanding

In [171]:
marketing_campaigns_clean.shape

(25000, 9)

In [172]:
marketing_campaigns_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   campaign_id     25000 non-null  int64
 1   campaign_name   25000 non-null  object
 2   campaign_type   25000 non-null  object
 3   target_segment  23530 non-null  object
 4   start_date      25000 non-null  object
 5   end_date        25000 non-null  object
 6   campaign_cost   25000 non-null  float64
 7   users_targeted  25000 non-null  int64
 8   conversions     25000 non-null  int64
dtypes: float64(1), int64(3), object(5)
memory usage: 1.7+ MB

#### Remove duplicates

In [173]:

print('Before duplicate removal:', marketing_campaigns_clean.shape)
marketing_campaigns_clean= marketing_campaigns_clean.drop_duplicates()
print('After duplicate removal:', marketing_campaigns_clean.shape)

Before duplicate removal: (25000, 9)
After duplicate removal: (25000, 9)

 #### Checking null values

In [174]:
marketing_campaigns_clean.isna().sum()

campaign_id          0
campaign_name        0
campaign_type        0
target_segment    1470
start_date           0
end_date             0
campaign_cost        0
users_targeted       0
conversions          0
dtype: int64

#### Convert date/time columns

In [175]:
marketing_campaigns_clean['start_date'] = pd.to_datetime(marketing_campaigns_clean['start_date'], errors='coerce')
marketing_campaigns_clean['end_date'] = pd.to_datetime(marketing_campaigns_clean['end_date'], errors='coerce')

#### Handling missing values

In [176]:
marketing_campaigns_clean['target_segment'] = marketing_campaigns_clean.groupby('campaign_type')['target_segment']\
.transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else None))

#### Check for negative values

In [177]:
print((marketing_campaigns_clean['campaign_cost'] < 0).sum())
print((marketing_campaigns_clean['users_targeted'] < 0).sum())
print((marketing_campaigns_clean['conversions'] < 0).sum())

0
0
0

#### Checking if convertions greater than user_targeted

In [178]:
invalid_rows = marketing_campaigns_clean[marketing_campaigns_clean['conversions'] > marketing_campaigns_clean['users_targeted']]
invalid_rows

Empty DataFrame
Columns: [campaign_id, campaign_name, campaign_type, target_segment, start_date, end_date, campaign_cost, users_targeted, conversions]
Index: []

In [179]:
marketing_campaigns_clean.isna().sum()

campaign_id       0
campaign_name     0
campaign_type     0
target_segment    0
start_date        0
end_date          0
campaign_cost     0
users_targeted    0
conversions       0
dtype: int64

In [180]:
marketing_campaigns_clean.shape

(25000, 9)

In [181]:
marketing_campaigns_clean.dtypes

campaign_id                int64
campaign_name             object
campaign_type             object
target_segment            object
start_date        datetime64[ns]
end_date          datetime64[ns]
campaign_cost            float64
users_targeted             int64
conversions                int64
dtype: object

#### Saving cleaned table

In [182]:
marketing_campaigns_clean.to_csv(r"C:\Users\DELL\Downloads\Movie_Ott_Project_File\Clean_file Csv\marketing_campaigns1.csv",index = False)

# Playback event table

In [183]:
playback_events_clean =playback_events.copy()

 ## Data Understanding

In [184]:
playback_events_clean.shape

(4000000, 9)

In [185]:
playback_events_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000000 entries, 0 to 3999999
Data columns (total 9 columns):
 #   Column               Dtype
---  ------               -----
 0   playback_event_id    int64
 1   watch_id             int64
 2   user_id              int64
 3   event_datetime       datetime64[ns]
 4   event_type           object
 5   buffering_seconds    int64
 6   video_quality        object
 7   internet_speed_mbps  float64
 8   error_code           object
dtypes: datetime64[ns](1), float64(1), int64(4), object(3)
memory usage: 274.7+ MB

#### Checking for duplicates

In [186]:

print('Before duplicate removal:',playback_events_clean.shape)
playback_events_clean = playback_events_clean.drop_duplicates()
print('After duplicate removal:', playback_events_clean.shape)

Before duplicate removal: (4000000, 9)
After duplicate removal: (4000000, 9)

#### Finding for null values

In [187]:
playback_events_clean.isna().sum()

playback_event_id           0
watch_id                    0
user_id                     0
event_datetime              0
event_type                  0
buffering_seconds           0
video_quality               0
internet_speed_mbps         0
error_code             571430
dtype: int64

#### Convert Date/time datatypes

In [188]:
playback_events_clean['event_datetime'] = pd.to_datetime(playback_events_clean['event_datetime'], errors='coerce')

#### Standardization

In [189]:
playback_events_clean['event_type'] = (playback_events_clean['event_type'].str.strip().str.lower())

#### Handling null values

In [190]:
playback_events_clean['error_code'] = playback_events_clean.groupby('event_type')['error_code']\
.transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown Error'))

In [191]:
playback_events_clean.shape

(4000000, 9)

In [192]:
playback_events_clean.dtypes

playback_event_id               int64
watch_id                        int64
user_id                         int64
event_datetime         datetime64[ns]
event_type                     object
buffering_seconds               int64
video_quality                  object
internet_speed_mbps           float64
error_code                     object
dtype: object

In [193]:
playback_events_clean.isna().sum()

playback_event_id      0
watch_id               0
user_id                0
event_datetime         0
event_type             0
buffering_seconds      0
video_quality          0
internet_speed_mbps    0
error_code             0
dtype: int64

#### Saving the datafile

In [195]:
playback_events_clean.to_csv(r"C:\Users\DELL\Downloads\Movie_Ott_Project_File\Clean_file Csv\playback_events1.csv",index = False)

# Ratings Reviews Table

In [196]:
ratings_reviews_clean=ratings_reviews.copy()

## Data Understanding

In [197]:
ratings_reviews_clean.shape

(1000000, 7)

In [198]:
ratings_reviews_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   review_id        1000000 non-null  int64
 1   user_id          1000000 non-null  int64
 2   content_id       1000000 non-null  int64
 3   rating           1000000 non-null  int64
 4   review_text      888889 non-null   object
 5   review_date      1000000 non-null  object
 6   sentiment_label  909091 non-null   object
dtypes: int64(4), object(3)
memory usage: 53.4+ MB

#### Removing Duplicates

In [199]:

print('Before duplicate removal:', ratings_reviews_clean.shape)
ratings_reviews_clean = ratings_reviews_clean.drop_duplicates()
print('After duplicate removal:',ratings_reviews_clean.shape)

Before duplicate removal: (1000000, 7)
After duplicate removal: (1000000, 7)

#### Finding null values

In [200]:
ratings_reviews_clean.isna().sum()

review_id               0
user_id                 0
content_id              0
rating                  0
review_text        111111
review_date             0
sentiment_label     90909
dtype: int64

#### Convert Date/Time Datatype

In [201]:
ratings_reviews_clean['review_date']=pd.to_datetime(ratings_reviews_clean['review_date'],errors='coerce')

#### Handling null values

In [202]:
ratings_reviews_clean['review_text']=ratings_reviews_clean['review_text'].fillna('No Review')

#### Standardize

In [203]:
ratings_reviews_clean['sentiment_label'] =ratings_reviews_clean['sentiment_label'].str.title()

In [204]:
def get_sentiment(rating):
    if rating >= 4:
        return 'Positive'
    elif rating == 3:
        return 'Neutral'
    else:
        return 'Negative'

ratings_reviews_clean['sentiment_label'] = ratings_reviews_clean['rating'].apply(get_sentiment)

In [205]:
ratings_reviews_clean.shape

(1000000, 7)

In [206]:
ratings_reviews_clean.dtypes

review_id                   int64
user_id                     int64
content_id                  int64
rating                      int64
review_text                object
review_date        datetime64[ns]
sentiment_label            object
dtype: object

In [207]:
ratings_reviews_clean.isna().sum()

review_id          0
user_id            0
content_id         0
rating             0
review_text        0
review_date        0
sentiment_label    0
dtype: int64

#### Saving the datafile

In [208]:
ratings_reviews_clean.to_csv(r"C:\Users\DELL\Downloads\Movie_Ott_Project_File\Clean_file Csv\ratings_reviews_clean1.csv",index = False)